# Torch tutorial

In [3]:
import torch

print("Toch is available?",torch.cuda.is_available())
print("GPU model: ",torch.cuda.get_device_name(0))

Toch is available? True
GPU model:  NVIDIA GeForce RTX 4060 Ti


## Tensors

### Empty tensors

In [5]:
# to create a empty tensor
x = torch.empty(3)
x

tensor([2.2766e-35, 0.0000e+00, 0.0000e+00])

In [6]:
torch.empty(3,4)

tensor([[4.9400e-34, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.2711e-37, 0.0000e+00, 1.0842e-19, 0.0000e+00],
        [2.7485e+20, 1.6928e+22, 7.4086e+28, 1.7728e+28]])

In [7]:
torch.empty(size=(3, 4, 2))

tensor([[[1.0616e+21, 1.7106e-04],
         [1.0811e-05, 1.4580e-19],
         [1.1495e+24, 3.0881e+29],
         [1.5766e-19, 7.3313e+22]],

        [[7.2151e+22, 2.8404e+29],
         [2.3089e-12, 1.9421e+31],
         [2.7491e+20, 6.1949e-04],
         [7.3389e+28, 1.8179e+31]],

        [[2.1707e-18, 1.9284e+31],
         [3.2314e-18, 9.6635e-06],
         [5.4450e-05, 1.0481e-11],
         [2.1238e+20, 1.6971e-07]]])

### Tensor zeros, ones, and randn

In [11]:
torch.zeros(size=(3, 3), dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [10]:
torch.ones(size=(3, 3), dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
#To work with random numbers
torch.manual_seed(1)

In [16]:
torch.rand(size=(3,3))

tensor([[0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980]])

### Operations

#### Explicit operations

In [17]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x + y
print(z)

z = torch.add(x,y)
print(z)

tensor([[1.3533, 0.9399],
        [0.6536, 0.7220]])
tensor([[1.3533, 0.9399],
        [0.6536, 0.7220]])


In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x - y
print(z)

z = torch.sub(x,y)
print(z)

tensor([[ 0.6404, -0.1411],
        [-0.1190,  0.3118]])
tensor([[ 0.6404, -0.1411],
        [-0.1190,  0.3118]])


In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x * y
print(z)

z = torch.mul(x,y)
print(z)

tensor([[0.5105, 0.7519],
        [0.0093, 0.0360]])
tensor([[0.5105, 0.7519],
        [0.0093, 0.0360]])


In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x / y
print(z)

z = torch.div(x,y)
print(z)

tensor([[0.0344, 0.9671],
        [0.9480, 1.4447]])
tensor([[0.0344, 0.9671],
        [0.9480, 1.4447]])


#### Implicit operations

In [25]:
x = torch.ones(1,2)
y = torch.ones(1,2)
print(y)

y.add_(x)  # if it contains "_", it will change the original value
print(y)

tensor([[1., 1.]])
tensor([[2., 2.]])


### Get items

In [30]:
x = torch.rand(5, 3)
print(x)

print(x[0])
print(x[0][0])
print(x[0][0].item())
print(x[:-1,1:2])

tensor([[0.6608, 0.8735, 0.9741],
        [0.1682, 0.5625, 0.8731],
        [0.8622, 0.8106, 0.1381],
        [0.1399, 0.1976, 0.5628],
        [0.9983, 0.1842, 0.7664]])
tensor([0.6608, 0.8735, 0.9741])
tensor(0.6608)
0.6608113646507263
tensor([[0.8735],
        [0.5625],
        [0.8106],
        [0.1976]])


### View element

In [44]:
x = torch.rand(5, 3)
print(x)
print(x.view(15))
print(x.view(-1, 5))
print(x.T)
x.size() , x.shape

tensor([[0.9544, 0.9371, 0.2165],
        [0.9892, 0.6237, 0.1679],
        [0.7737, 0.1267, 0.9620],
        [0.1786, 0.6414, 0.6523],
        [0.6189, 0.9147, 0.2923]])
tensor([0.9544, 0.9371, 0.2165, 0.9892, 0.6237, 0.1679, 0.7737, 0.1267, 0.9620,
        0.1786, 0.6414, 0.6523, 0.6189, 0.9147, 0.2923])
tensor([[0.9544, 0.9371, 0.2165, 0.9892, 0.6237],
        [0.1679, 0.7737, 0.1267, 0.9620, 0.1786],
        [0.6414, 0.6523, 0.6189, 0.9147, 0.2923]])
tensor([[0.9544, 0.9892, 0.7737, 0.1786, 0.6189],
        [0.9371, 0.6237, 0.1267, 0.6414, 0.9147],
        [0.2165, 0.1679, 0.9620, 0.6523, 0.2923]])


(torch.Size([5, 3]), torch.Size([5, 3]))

In [39]:
y = x.view(-1, 15)
y, y.size()

(tensor([[0.9595, 0.0677, 0.1103, 0.4830, 0.2296, 0.6789, 0.3075, 0.2652, 0.5283,
          0.8619, 0.1483, 0.7348, 0.8212, 0.9891, 0.1500]]),
 torch.Size([1, 15]))

In [40]:
x = torch.rand(5, 3)
print(x)
x.size()

tensor([[0.6211, 0.1303, 0.9269],
        [0.3060, 0.8012, 0.5149],
        [0.4611, 0.4840, 0.5850],
        [0.7357, 0.5802, 0.6525],
        [0.0502, 0.8643, 0.9359]])


torch.Size([5, 3])

### to numpy

In [56]:
a = torch.tensor([1, 2, 3])
print(a)

c =a.numpy()
print(c)

tensor([1, 2, 3])
[1 2 3]


In [57]:
a.add_(2) # with in-place operation, if yuou use a.numpy it will change the variable assidned like 'b'
print(c)

[3 4 5]


In [60]:
import numpy as np
a= np.zeros((2,2))
print(a)
b = torch.from_numpy(a) # it creates a copy of a
print(b)

[[0. 0.]
 [0. 0.]]
tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


## Working with GPU and CPU

In [68]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [70]:
z = z.to("cpu")
z

tensor([2., 2., 2., 2., 2.])

## Autogradde

In [62]:
x = torch.randn(3, requires_grad=False)
print(x)

y = x+2
print(y)

z = y*y*2
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([0.7525, 0.1168, 0.2494])
tensor([2.7525, 2.1168, 2.2494])
tensor(11.4112)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [67]:
!pwd  #ubuntu root

/home/moises


In [66]:
!ls /mnt/c/Users/User/Documents/codes/DL/images/

autograd.PNG


![Image Description](images/autograd.PNG)

In [72]:
## Ejemplo 1

#forward pass
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)


# backward pass
z = y*y*2
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)


tensor([ 0.2257, -0.0488, -0.3331], requires_grad=True)
tensor([2.2257, 1.9512, 1.6669], grad_fn=<AddBackward0>)
tensor(7.6931, grad_fn=<MeanBackward0>)
tensor([2.9676, 2.6016, 2.2226])


In [74]:
## Ejemplo 2
weights = torch.ones(4, requires_grad = True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])


In [80]:
## Ejemplo 3

weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()


## Backprpagation en pytorch

In [82]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

#forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

#backward pass
loss.backward()
print(w.grad)

#update weights
#next forward and backward pass

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
